[project]
name = "ai-news-aggregator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< HEAD
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "apscheduler>=3.11.2",
    "beautifulsoup4>=4.14.3",
    "black>=26.1.0",
    "diskcache>=5.6.3",
    "fastapi>=0.129.0",
    "feedparser>=6.0.12",
    "google-api-python-client>=2.190.0",
    "httpx>=0.28.1",
    "lxml>=6.0.2",
    "newspaper3k>=0.2.8",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "python-dotenv>=1.2.1",
    "pytube>=15.0.0",
    "requests>=2.32.5",
    "ruff>=0.15.1",
    "sqlalchemy>=2.0.46",
    "tenacity>=9.1.4",
    "uvicorn>=0.40.0",
    "youtube-transcript-api>=1.2.4",
=======
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "feedparser>=6.0.12",
    "openai>=2.21.0",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.46",
>>>>>>> 14e872d9dd90cc63feae7500c8771c9d6754574e
]
